parameters:
    payplug.method.identifier_prefix: 'payplug'

services:
    payplug.generator.payplug_config_identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%payplug.method.identifier_prefix%'

    payplug.integration.channel:
        class: Payplug\Bundle\PaymentBundle\Integration\PayplugChannelType
        public: true
        tags:
            - { name: oro_integration.channel, type: payplug }

    Payplug\Bundle\PaymentBundle\Integration\PayplugChannelType:
        alias: payplug.integration.channel

    payplug.integration.transport:
        class: Payplug\Bundle\PaymentBundle\Integration\PayplugTransport
        public: false
        tags:
            - { name: oro_integration.transport, type: payplug, channel_type: payplug }

    Payplug\Bundle\PaymentBundle\Integration\PayplugTransport:
        alias: payplug.integration.transport

    payplug.factory.payplug_config:
        class: Payplug\Bundle\PaymentBundle\Method\Config\Factory\PayplugConfigFactory
        public: false
        arguments:
            - '@oro_locale.helper.localization'
            - '@payplug.generator.payplug_config_identifier'

    Payplug\Bundle\PaymentBundle\Method\Config\Factory\PayplugConfigFactory:
        alias: payplug.factory.payplug_config

    payplug.payment_method.config.provider:
        class: Payplug\Bundle\PaymentBundle\Method\Config\Provider\PayplugConfigProvider
        arguments:
            - '@doctrine'
            - '@logger'
            - '@payplug.factory.payplug_config'

    Payplug\Bundle\PaymentBundle\Method\Config\Provider\PayplugConfigProvider:
        alias: payplug.payment_method.config.provider

    payplug.factory.method_view.payplug:
        class: Payplug\Bundle\PaymentBundle\Method\View\Factory\PayplugViewFactory
        public: false
        arguments:
            - '@payplug.factory.payplug_config'

    Payplug\Bundle\PaymentBundle\Method\View\Factory\PayplugViewFactory:
        alias: payplug.factory.method_view.payplug

    payplug.payment_method_view_provider.payplug:
        class: Payplug\Bundle\PaymentBundle\Method\View\Provider\PayplugViewProvider
        public: false
        arguments:
            - '@payplug.payment_method.config.provider'
            - '@payplug.factory.method_view.payplug'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    Payplug\Bundle\PaymentBundle\Method\View\Provider\PayplugViewProvider:
        alias: payplug.payment_method_view_provider.payplug

    payplug.service.gateway:
        class: Payplug\Bundle\PaymentBundle\Service\Gateway
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@property_accessor'
            - '@router'
            - '@payplug.service.logger'
            - '@oro_platform.composer.version_helper'

    Payplug\Bundle\PaymentBundle\Service\Gateway:
        alias: payplug.service.gateway

    payplug.factory.method.payplug:
        class: Payplug\Bundle\PaymentBundle\Method\Factory\PayplugPaymentMethodFactory
        public: false
        arguments:
            - '@payplug.service.gateway'

    Payplug\Bundle\PaymentBundle\Method\Factory\PayplugPaymentMethodFactory:
        alias: payplug.factory.method.payplug

    payplug.payment_method_provider.payplug:
        class: Payplug\Bundle\PaymentBundle\Method\Provider\PayplugMethodProvider
        public: true
        arguments:
            - '@payplug.payment_method.config.provider'
            - '@payplug.factory.method.payplug'
        tags:
            - { name: oro_payment.payment_method_provider }

    Payplug\Bundle\PaymentBundle\Method\Provider\PayplugMethodProvider:
        alias: payplug.payment_method_provider.payplug

    payplug.datagrid.order_payment_transactions.action_permission_provider:
        class: Payplug\Bundle\PaymentBundle\Datagrid\ActionPermissionProvider
        public: true
        arguments:
            - '@payplug.payment_method_provider.payplug'
            - '@doctrine.orm.entity_manager'

    Payplug\Bundle\PaymentBundle\Datagrid\ActionPermissionProvider:
        alias: payplug.datagrid.order_payment_transactions.action_permission_provider

    payplug.service.logger:
        class: Payplug\Bundle\PaymentBundle\Service\Logger
        arguments:
            - '@payplug.service.anonymizer'
        calls:
            - [setLogger, ['@logger']]

    Payplug\Bundle\PaymentBundle\Service\Logger:
        alias: payplug.service.logger

    payplug.service.anonymizer:
        class: Payplug\Bundle\PaymentBundle\Service\Anonymizer

    Payplug\Bundle\PaymentBundle\Service\Anonymizer:
        alias: payplug.service.anonymizer

    payplug.handler.payment_transaction:
        class: Payplug\Bundle\PaymentBundle\Handler\PaymentTransactionHandler
        public: true
        arguments:
            - '@payplug.payment_method_provider.payplug'
            - "@payplug.service.refund_manager"

    Payplug\Bundle\PaymentBundle\Handler\PaymentTransactionHandler:
        alias: payplug.handler.payment_transaction

    payplug.service.refund_manager:
        class: Payplug\Bundle\PaymentBundle\Service\RefundManager
        arguments:
            - '@doctrine.orm.entity_manager'

    Payplug\Bundle\PaymentBundle\Service\RefundManager:
        alias: payplug.service.refund_manager

    payplug.validator.payment_rule.currency_is_euro:
        class: Payplug\Bundle\PaymentBundle\Validator\Constraints\CurrencyIsEuroValidator
        arguments:
            - '@payplug.payment_method_provider.payplug'
        tags:
            - { name: validator.constraint_validator, alias: payplug.validator.payment_rule.currency_is_euro }

    Payplug\Bundle\PaymentBundle\Validator\Constraints\CurrencyIsEuroValidator:
        alias: payplug.validator.payment_rule.currency_is_euro

    payplug.formatter.money_value_type:
        alias: oro_currency.formatter.money_value_type
        public: true
