operations:
    payplug_payment_transaction_refund:
        label: payplug.order.action.refund.label
        button_options:
            icon: fa-credit-card
        applications: [default]
        datagrids:
            - order-payment-transactions-grid
        order: 50
        preactions:
            - '@call_service_method':
                  service: payplug.payment_method_provider.payplug
                  method: getPaymentMethod
                  method_parameters: [$.data.paymentMethod]
                  attribute: $.paymentMethod
            - '@call_method':
                  conditions:
                      '@and':
                          -   '@instanceof': [$.paymentMethod, Payplug\Bundle\PaymentBundle\Method\Payplug]
                  object: $.paymentMethod
                  method: getMaximumRefundAmount
                  method_parameters: [$.data]
                  attribute: $.maximumAmount
            - '@call_service_method':
                  service: oro_currency.formatter.money_value_type
                  method: format
                  method_parameters: [0.1]
                  attribute: $.minFormattedAmount
            - '@call_service_method':
                  service: oro_currency.formatter.money_value_type
                  method: format
                  method_parameters: [$.maximumAmount]
                  attribute: $.maxFormattedAmount
            - '@trans':
                  id: payplug.constraints.payment_refund.min_message
                  attribute: $.minMessage
                  params:
                      '{min}': $.minFormattedAmount
            - '@trans':
                  id: payplug.constraints.payment_refund.max_message
                  attribute: $.maxMessage
                  params:
                      '{max}': $.maxFormattedAmount
        preconditions:
            '@and':
                - '@equal': [$.data.entity_class, 'Oro\Bundle\OrderBundle\Entity\Order']
                - '@equal': [$.data.action, 'purchase']
                - '@equal': [$.data.active, true]
                - '@equal': [$.data.successful, true]
                - '@not_empty': $.paymentMethod
                - '@instanceof': [$.paymentMethod, Payplug\Bundle\PaymentBundle\Method\Payplug]
        attributes:
            payplugAmount:
                label: Amount
                type: string
            currency:
                label: Currency
                type: string
        form_options:
            attribute_fields:
                payplugAmount:
                    form_type: Symfony\Component\Form\Extension\Core\Type\NumberType
                    options:
                        required: true
                        constraints:
                            - NotBlank: ~
                            - Payplug\Bundle\PaymentBundle\Validator\Constraints\LocalizedRange:
                                  min: $.minFormattedAmount
                                  max: $.maxFormattedAmount
                                  minMessage: $.minMessage
                                  maxMessage: $.maxMessage
                currency:
                    form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
            attribute_default_values:
                payplugAmount: $.data.amount
        form_init:
            - '@assign_value': [$.payplugAmount, $.maximumAmount]
        actions:
            - '@call_service_method':
                  service: payplug.handler.payment_transaction
                  method: refund
                  method_parameters: [$.data, $.form]
                  attribute: $.result
            - '@flash_message':
                  conditions:
                      '@equal': [$.result, true]
                  message: payplug.order.action.refund.message
                  type: 'success'
            - '@refresh_grid': order-payment-transactions-grid
