operations:
    payplug_payment_transaction_refund:
        label: payplug.order.action.refund.label
        button_options:
            icon: fa-credit-card
        applications: [default]
        datagrids:
            - order-payment-transactions-grid
        order: 50
        preactions:
            - '@call_service_method':
                service: oro_payment.payment_method.composite_provider
                method: getPaymentMethod
                method_parameters: [$.data.paymentMethod]
                attribute: $.paymentMethod
            - '@call_method':
                object: $.paymentMethod
                method: getMaximumRefundAmount
                method_parameters: [$.data]
                attribute: $.maximumAmount
        preconditions:
            '@and':
                - '@equal': [$.data.entity_class, '%oro_order.entity.order.class%']
                - '@equal': [$.data.action, 'purchase']
                - '@equal': [$.data.active, true]
                - '@equal': [$.data.successful, true]
                - '@not_empty': $.paymentMethod
                - '@instanceof': [$.paymentMethod, Payplug\Bundle\PaymentBundle\Method\Payplug]
        attributes:
            payplugAmount:
                label: Amount
                type: string
            currency:
                label: Currency
                type: string
        form_options:
            attribute_fields:
                payplugAmount:
                    form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                    options:
                        required: true
                        constraints:
                            -   NotBlank: ~
                            -   Range:
                                    min: 0.10
                                    max: $.maximumAmount
                currency:
                    form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
            attribute_default_values:
                payplugAmount: $.data.amount
        form_init:
            - '@assign_value': [$.payplugAmount, $.maximumAmount]
        actions:
            - '@call_service_method':
                service: payplug.handler.payment_transaction
                method: refund
                method_parameters: [$.data, $.form]
                attribute: $.result
            - '@flash_message':
                conditions:
                    '@equal': ['$.result[successful]', true]
                message: 'Pouet'
                message_parameters:
                    'amount': $.form.amount
                type: 'success'
            - '@refresh_grid': order-payment-transactions-grid